apiVersion: v1
kind: Service
metadata:
  name: velocity-proxy
  labels:
    app: velocity-proxy
spec:
  type: LoadBalancer
  selector:
    app: velocity-proxy
  ports:
    - name: minecraft
      port: 25565
      targetPort: 25565
      protocol: TCP
    - name: bedrock
      port: 19132
      targetPort: 19132
      protocol: UDP
