[workspace]
members = [
    "spec",
    "corelib",
    "core",
    "api",
]
resolver = "2"

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["std"] }
