apiVersion: v1
kind: Service
metadata:
  name: dlog-api
  namespace: dlog
  labels:
    app: dlog-api
spec:
  selector:
    app: dlog-api
  ports:
    - name: http
      port: 8888
      targetPort: 8888
      protocol: TCP
  type: ClusterIP
