[package]
name = "dlog-core"
version = "0.1.0"
edition = "2021"

[dependencies]
dlog-spec = { path = "../spec" }
dlog-corelib = { path = "../corelib" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
