[package]
name = "dlog-corelib"
version = "0.5.0"
edition = "2021"

[dependencies]
dlog-spec = { path = "../spec" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
